### ISSUE TITLE
roarr 3.2.3 error filter

### ISSUE THREAD

**Issue by dmpvost** [gajus/roarr-cli#10]
I got a crash with the new version of roarr-cli 3.2.3

> [App] ~/struct/node_modules/@roarr/cli/dist/bin/index.js:60
[App]     if (roarrConfiguration?.filterFunction) {
[App]                            ^
[App] 
[App] SyntaxError: Unexpected token '.'
[App]     at wrapSafe (internal/modules/cjs/loader.js:931:16)
[App]     at Module._compile (internal/modules/cjs/loader.js:979:27)
[App]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
[App]     at Module.load (internal/modules/cjs/loader.js:879:32)
[App]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
[App]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[App]     at internal/main/run_main_module.js:17:47

When i replace `roarrConfiguration?.filterFunction` by `roarrConfiguration.filterFunction` it work again

**Comment by gajus** [comment]
That's because tsconfig.json is misconfigured. Need to correct target to support lower Node.js versions.

**Comment by dmpvost** [comment]
how fix it for my side? 

I'm running node 12

**Comment by boedy** [comment]
@dmpvost I believe @gajus meant he needs to update the `tsconfig.json` included in this repo to support older NodeJS versions.

I'm running into the same issue on node12. Node 14 works.

**Comment by gajus** [comment]
* v3 made compatible with node 10
* v4 is compatible with node 12+

**Comment by boedy** [comment]
@gajus I just tried out the new package. Both version 3 and version 4 still don't work on Node 12. I just compiled the master branch to test out the right `tsconfig`. Setting `target` to `es2019` seems to do the trick. [Source I used for reference](https://stackoverflow.com/questions/59787574/typescript-tsconfig-settings-for-node-js-12)

**Comment by gajus** [comment]
Sorry about that. semantic-release process failed. Manually released 3.9.0.

**Comment by boedy** [comment]
No worries. Just to verify, version 4 will not support Node 12?

**Comment by gajus** [comment]
No. I am reluctant to transpile down because of performance impact.

I am planning to create a benchmark for some of the functionality.

Once that is out, I will compare performance impact with / without transpilation and decide if we should re-introduce node 10 / 12 support.
