### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by hallvors** [gajus/roarr-cli#11]
```
$> ~/.config/yarn/global/node_modules/.bin/roarr --help

~/.config/yarn/global/node_modules/@roarr/cli/dist/bin/index.js:60
    if (roarrConfiguration?.filterFunction) {
                           ^

SyntaxError: Unexpected token '.'
```
Not that familiar with Typescript but there's perhaps a question mark that should not be there on this line?
https://github.com/gajus/roarr-cli/blob/master/src/bin/index.ts#L75

**Comment by gajus** [comment]
https://github.com/gajus/roarr-cli/issues/10
