### ISSUE TITLE
Allow choosing different property names to written message objects

### ISSUE THREAD

**Issue by deankevorkian** [gajus/roarr-cli#13]
when collecting logs with fluentd, from the log streams of our pods on our k8s cluster, the messages would not be transferred to Elastic. Seems like this happens due to fluentd having issues collecting the json parsed log messages, when the json contains a property by name of "time". I am still unsure if this is default fluentd behavior, or something faulty in our own configuration.

However, I'd like to know if it's possible to provide another API in the library where one could manipulate the structure of the json (for that matter, choosing different property names for the object written by Roarr).

As of now, we simply patch the write method to parse the stringified json back to an object, rename the property and strigify it again, something we'd like to avoid. I can open a PR myself if it helps, but I'd like to know how you suggest (if you want to support such thing) we can make it.

We can have an interception function that manipulates the object before stringifying it (but will require changing the schema because Roarr uses fast-json-stringify. Maybe we can provide a "translation map" that translates every default property name to a desired one, maybe we can provide it through environment variables instead of a public api in the library.

**Comment by gajus** [comment]
@deankevorkian Transferred this issue to @roarr/cli.

The goal with roarr (the logger) is to keep it standardised, so that other programs could be built having guarantees around the shape of the logs. Therefore, modifying the structure of the logs is a no-go.

However, this is a perfect use case for a transform in a project such as @roarr/cli (or even a utility built adhoc for this use case). The benefit of doing it out of process is that it is becomes a non-blocking operation and it works in a different thread.

I cannot think of a straightforward generic interface for a transform though. Open to ideas.

**Comment by squirmy** [comment]
This would be a pretty handy feature to have. Though I believe there will be circumstances where a project such as @roarr/cli is not able to be used.

For example: When running within AWS Lambda you're not able to pipe stdout to a separate process. These logs get pulled into CloudWatch, which can then be analyzed with CloudWatch Insights. The standard set of fields will work fine, until you want to standardize your logging format across different technologies / stacks. Then there's no real option here without using another log aggregation tool.

I see the benefit of keeping the format standardised in roarr. Though for these circumstances it would be super useful to be able to transform the log format in process.

I wonder if there's a middle ground here?

**Comment by gajus** [comment]
There is nothing stopping you from overriding `globalThis.ROARR.write`.

https://github.com/gajus/roarr#roarr-anti-patterns-overriding-globalthis-roarr-write-in-node-js

Sounds like `@roarr/aws-lambda` would be a handy utility.
