### ISSUE TITLE
Filter with roar

### ISSUE THREAD

**Issue by dmpvost** [gajus/roarr-cli#3]
Hi ! 

I'm trying to use roarr-cli and filter result, but I failed

Basically: this work; as it's show on the tutorial

> roarr  --exclude-alien --output-format json --filter-expression '{"context.logLevel":{gt:10}}'

But I want to make a more complexe expression, and filter context.package. 
Nothing I tried work. It's wrote we can use JQ, but I don't know how to do it

with jq, I would like to add something like this : 

> | jq 'select(.context.package | contains(\"dev\"))'

and finally, pretty print on the end

any help? thank!

**Comment by gajus** [comment]
You can either:

1. Write filters using JavaScript https://github.com/gajus/roarr-cli#roarr-configuration-file
2. Refer to the documentation of searchjs https://www.npmjs.com/package/searchjs

**Comment by dmpvost** [comment]
I made some improvement, not easy, but start to be fine
