### ISSUE TITLE
Add new env variable to ROARR

### ISSUE THREAD

**Issue by dmpvost** [gajus/roarr-cli#4]
It would be nice, if we can add some options to ROARR with env.

exemple is better than word :

ROARR_USE_COLORS=true
ROARR_OUTPUT_FORMAT=pretty

I have one use case, when I make unit testing with my IDE,
I don't find the way to put extra parameters.

I use web storm with JEST.

**Comment by gajus** [comment]
```env
ROARR_USE_COLORS=true
ROARR_OUTPUT_FORMAT=pretty

```

This should already work. What are you suggesting?

**Comment by dmpvost** [comment]
Okay maybe I didn't see it in the documentation

right now, we should use roarr like this, 
`ROARR_LOG=TRUE node index.js`

or with options : 

`ROARR_LOG=TRUE node index.js | roarr --use-colors --output-format pretty`

but in my case, I cannot use pipe. So my suggestion is to add some others variable in `process.env`

`ROARR_USE_COLORS=true`
`ROARR_OUTPUT_FORMAT=pretty`

or put params like this : 

`ROARR_LOG=TRUE; ROARR_USE_COLORS=true; ROARR_OUTPUT_FORMAT=pretty;  node index.js`

**Comment by gajus** [comment]
But you can already do that.

**Comment by gajus** [comment]
```bash
$ export ROARR_USE_COLORS=true
$ export ROARR_OUTPUT_FORMAT=pretty
$ export ROARR_LOG=TRUE
$ node index.js | roarr

```

should work just fine. If not, report a bug.

**Comment by dmpvost** [comment]
okay, I understand, I cannot use `| roarr`

**Comment by gajus** [comment]
Answered in https://github.com/gajus/roarr/issues/30#issuecomment-607260158

Responsibility of formatting logs is not the responbility of the main app. That would have all sorts of perfrmance implications that you do not want.

**Comment by dmpvost** [comment]
Thank, I understand, it's just for unit testing one-by-bone, so it's useless if it have some bad performance

**Comment by gajus** [comment]
> Thank, I understand, it's just for unit testing one-by-bone, so it's useless if it have some bad performance

There are tons of workarounds. You can use something like https://github.com/gajus/output-interceptor and parse it however you want.
